---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: elk
spec: {}
status: {}

---
apiVersion: v1
kind: LimitRange
metadata:
  name: es-limits
spec:
  limits:
    - max:
        memory: 512Mi
        cpu:  800m
      min:
        memory: 256Mi
        cpu: 200m
      type: Container
---
apiVersion: v1
kind: Service
metadata:
  name: es
spec:
  selector:
    role: master
  ports:
  - name: transport
    port: 9300
    protocol: TCP
  clusterIP: None
