apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat
data:
  filebeat.yml: |
    #=========================== Filebeat inputs =============================

    filebeat.inputs:
    - type: log
      paths:
      - /var/log/*.log
      #exclude_lines: [u'^DBG']
      #include_lines: [u'^ERR', u'^WARN']
      #exclude_files: [u'.gz$']
      #fields:
      #  level: debug
      #  review: 1
      ### Multiline options
      #multiline.pattern: ^\[
      #multiline.negate: false
      #multiline.match: after
    #============================= Filebeat modules ===============================
    filebeat.config.modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: True
    reload.period: 10s
    #================================ General =====================================
    #name:
    #tags: ["service-X", "web-tier"]
    #fields:
    #  env: staging
    #--------------------------- Kafka Output -------------------------------------
    output.kafka:
    # initial brokers for reading cluster metadata
    hosts:  [  ]
    topic: 'test_topic'
    partition.round_robin:
    reachable_only: false
    required_acks: 1
    compression: gzip
    max_message_bytes: 1000000
    #================================ Processors ====================================
    processors:
    - add_host_metadata: ~
    - add_cloud_metadata: ~
    - add_docker_metadata: ~
    - add_kubernetes_metadata: ~
    #================================ Logging =====================================
    #logging.level: debug
    #logging.selectors: ["*"]

