---
apiVersion: v1
kind: ConfigMap
metadata:
  name: es-master
  labels:
    role: master
data:
  elasticsearch.yml: |
    cluster.name: "SuperGun"
    bootstrap.memory_lock: False
    network.host: "0.0.0.0"
    discovery.zen.ping.unicast.hosts: es
    discovery.zen.minimum_master_nodes: 1
    action.destructive_requires_name: true
    node.master: true
    node.data: false
    node.ingest: false
    cluster.remote.connect: false
  ES_JAVA_OPTS: -Xms512m -Xmx512m

---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: es-master
  labels:
    role: master
spec:
  replicas: 1
  selector:
    matchLabels:
      role: master
  template:
    metadata:
      labels:
        role: master
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: sysctl-config
        image: busybox
        securityContext: 
          privileged: true
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
      containers:
      - name: es-master
        image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
        securityContext:
          privileged: true
          runAsUser: 1000
          capabilities:
            add:
            - IPC_LOCK
            - SYS_RESOURCE
        env:
        - name: ES_JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: es-master
              key: ES_JAVA_OPTS
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /_cluster/health?local=true
            port: 9200
        ports:
        - containerPort: 9200
          name: es-http
        - containerPort: 9300
          name: es-transport
        volumeMounts:
        - name: es-master-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
      volumes:
      - name: es-master-config
        configMap:
          name: es-master
          items:
            - key: elasticsearch.yml
              path: elasticsearch.yml
        


