apiVersion: v1
kind: Service 
metadata:
  name: es-service
  labels:
    role: client
spec:
  selector:
    role: client
  ports:
  - name: es-http
    port: 8080
    targetPort: 9200
  type: NodePort
