apiVersion: v1
kind: Service
metadata:
  name: es-master
  namespace: elk
  labels:
    role: master
spec:
  selector:
    role: master
  ports:
  - name: transport
    port: 9300
    protocol: TCP
  clusterIP: None
