apiVersion: v1
kind: ConfigMap
metadata:
  name: es-data
  labels:
    role: data
data:
  elasticsearch.yml: |
    cluster.name: "SuperGun"
    bootstrap.memory_lock: False
    network.host: "0.0.0.0"
    discovery.zen.ping.unicast.hosts: es-master
    discovery.zen.minimum_master_nodes: 1
    action.destructive_requires_name: true
    node.master: false
    node.data: true
    node.ingest: false
    cluster.remote.connect: false
  ES_JAVA_OPTS: -Xms512m -Xmx512m
    
