apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-data
  labels:
    role: data
spec:
  accessModes:
  - "ReadWriteOnce"
  storageClassName: es-data
  resources:
    requests:
      storage: "2Gi"


  
