---
- name: Create main Logstash config
  template:
    src: "logstash.yml.j2"
    dest: "/etc/logstash/logstash.yml"
    owner: root
    group: root
    mode: 0600
  notify: Restart Logstash

- name: Create [ Pipe Line ] Input Configuration
  template:
    src: "input.conf.j2"
    dest: "/etc/logstash/conf.d/input.conf"
    owner: root
    group: root
    mode: 0600
  notify: Restart Logstash

- name: Create [ Pipe Line ] Filter Configuration
  template:
    src: "filter.conf.j2"
    dest: "/etc/logstash/conf.d/filter.conf"
    owner: root
    group: root
    mode: 0600
  notify: Restart Logstash

- name: Create [ Pipe Line ] Input Configuration
  template:
    src: "output.conf.j2"
    dest: "/etc/logstash/conf.d/output.conf"
    owner: root
    group: root
    mode: 0600
  notify: Restart Logstash


